spring.application.name=service-catalog-service

spring.datasource.url=jdbc:postgresql://localhost:5432/service-catalog
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest

server.port=8081